# Generated by Django 4.2.1 on 2023-06-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='author',
            field=models.CharField(max_length=250, verbose_name='Имя автора'),
        ),
    ]
