# Generated by Django 4.2.1 on 2023-06-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_pin_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='subTitle',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
