# Generated by Django 4.2.1 on 2023-06-07 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_pin_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('text_comment', models.TextField(max_length=500, verbose_name='Текст коммента')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.pin', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Коммент',
                'verbose_name_plural': 'Коментарии',
            },
        ),
    ]
